services:
  latest:
    build:
      args:
        PHP_VERSION: ""
    tty: true
    volumes:
      - .:/app/:delegated
  php80:
    build:
      args:
        PHP_VERSION: "8.0-"
    extends:
      service: latest
  php81:
    build:
      args:
        PHP_VERSION: "8.1-"
    extends:
      service: latest
  php82:
    build:
      args:
        PHP_VERSION: "8.2-"
    extends:
      service: latest
  php83:
    build:
      args:
        PHP_VERSION: "8.3-"
    extends:
      service: latest
  php84:
    build:
      args:
        PHP_VERSION: "8.4-rc-"
        XDEBUG_ENABLED: 0
    extends:
      service: latest
