#!/usr/bin/env php
<?php

/**
 * Static Analysis Results Baseliner (sarb).
 *
 * (c) Dave Liddament
 *
 * For the full copyright and licence information please view the LICENSE file distributed with this source code.
 */


declare(strict_types=1);

use DaveLiddament\StaticAnalysisBaseliner\Framework\Container\Container;

require_once __DIR__ . "/vendor/autoload.php";

$container = new Container();
$application = $container->getApplication();

$application->run();
